- name: docker-compose down
  register: result
  retries: 2
  delay: 5
  until: result is not failed
  docker_compose:
    project_src: "{{ DOCKER_COMPOSE_DIR }}"
    state: absent
  ignore_errors: yes

- name: remove images
  docker_compose:
    project_src: "{{ DOCKER_COMPOSE_DIR }}"
    remove_images: all
  ignore_errors: yes