# Generated by Django 2.2.4 on 2019-08-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20190816_1842"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card", old_name="name", new_name="card_name",
        ),
        migrations.RemoveField(model_name="card", name="duration",),
        migrations.RemoveField(
            model_name="cardcontainer", name="date_published",
        ),
        migrations.RemoveField(model_name="cardcontainer", name="duration",),
        migrations.RemoveField(model_name="cardcontainer", name="location",),
        migrations.AddField(
            model_name="cardcontainer",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cardcontainer",
            name="summary",
            field=models.CharField(max_length=200),
        ),
    ]
