# Generated by Django 2.2.4 on 2019-08-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20190816_2325"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_slug",
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="subcategory_slug",
            field=models.CharField(default=1, max_length=200),
        ),
    ]
