
# create super user - use existing logic automatically get the right container id?
docker exec -it 120f5edfb608 python manage.py createsuperuser


# docker compose update
# docker-compose down && docker-compose build && docker-compose up