- name: Create and upload postgres backup to AWS S3
  become_user: ubuntu
  shell: >
    cd {{ PORTFOLIO_ROOT_DIR }}/deployment &&
    source .env &&
    make postgres-dump-to-s3
  args:
    executable: /bin/bash
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"

- name: Download and restore postgres backup from AWS S3
  become_user: ubuntu
  shell: >
    cd {{ PORTFOLIO_ROOT_DIR }}/deployment &&
    source .env &&
    make postgres-restore-from-s3
  args:
    executable: /bin/bash
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"