---
# This playbook contains all actions that will be run on "local" host.


- name: Stop k8s cluster instances
  ec2:
    region: eu-west-3
    instance_tags:
        Type: "{{ INSTANCE_TAG_TYPE }}"
    state: stopped
  tags:
    - cluster-stop
