name: portfolio-env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.6.7
  - pip==19.3.1
  - black==19.10b0
  - git==2.24.0          # GPLv2
  - nginx==1.17.4        # BSD-2
  - postgresql==12.1     # PSQL
  - redis                # BSD-3
  - celery
  - ansible==2.9.2
  - awscli==1.16.309
  - pip:
      - pytest==4.0
      - pre-commit==1.20.0
      - pytest-cov==2.8.1
      - django==2.2.6
      - Pillow==6.2.1
      - django-tinymce4-lite==1.7.5
      - psycopg2==2.7.1
      - bump2version==0.5.11
      - django-redis==4.11.0
      - celery==4.4.0
      - django-celery-results==1.1.2
      - boto==2.49.0
      - botocore==1.13.45