name: portfolio-env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.6.7
  - pip
  - requests
  - black
  - pip:
      - pytest==4.0
      - pre-commit
      - pytest-cov
      - django==2.2.4
      - Pillow
      - django-tinymce4-lite