name: portfolio-env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.6.7
  - pip
  - requests
  - black
  - git               # GPLv2
  - nginx             # BSD-2
  - postgresql        # PSQL
  - redis             # BSD-3
  - pip:
      - pytest==4.0
      - pre-commit==1.20.0
      - pytest-cov==2.8.1
      - django==2.2.4
      - Pillow==6.2.1
      - django-tinymce4-lite==1.7.5
      - psycopg2==2.7.1
      - bump2version==0.5.11
      - django-redis==4.11.0