name: portfolio-env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.6.7
  - pip
  - requests
  - black
  - pip:
      - pytest==4.0
      - pre-commit==1.20.0
      - pytest-cov==2.8.1
      - django==2.2.4
      - Pillow==6.2.1
      - django-tinymce4-lite==1.7.5
      - psycopg2==2.5.2