# Install Packages

# Commenting `apt` modules due to 
# `Failed to lock apt for exclusive operation` error
# since some other (aws) application seems to be holding the apt lock.
# more info: https://serverfault.com/questions/716260/ansible-sudo-error-while-building-on-atlas

# - name: Install packages
#   become: yes
#   apt:
#     name: ['awscli', 'python3', 'python3-pip', 'make', 'curl']
#     update_cache: yes
#     state: present

# sudo apt-get autoclean
# sudo apt-get autoremove
# - name: Clean up
#   apt:
#     autoclean: yes
#     autoremove: yes

- name: Add python alias
  lineinfile:
    dest: /home/ubuntu/.bash_aliases
    line: alias python='python3'
    state: present
    insertafter: EOF
    create: True

- name: Install pip packages
  pip:
    name:
      - docker
      - docker-compose
      - boto3
      - botocore


# Install Docker

- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: no

- name: Add apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7EA0A9C3F273FCD8

- name: Install Docker-CE
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: true
    state: present

- name: Add the user to the docker group
  user:
    name: "{{ ANSIBLE_USER }}"
    groups: "{{ DOCKER_GROUP }}"
    append: yes

- name: Start docker on boot
  systemd:
    name: docker
    state: started
    enabled: yes


# Install docker-compose

- name: Fetch docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: "0755"


# Docker login

- name: Log into DockerHub
  docker_login:
    username: "{{ DOCKER_USER }}"
    password: "{{ DOCKER_PASSWORD }}"