# Generated by Django 2.2.4 on 2019-12-27 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("image", models.ImageField(upload_to="images")),
                ("category_slug", models.CharField(default=1, max_length=200)),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subcategory_name", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="images")),
                (
                    "subcategory_slug",
                    models.CharField(default=1, max_length=200),
                ),
                (
                    "category_name",
                    models.ForeignKey(
                        default=1,
                        on_delete="SET_DEFAULT",
                        to="main.Category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Sub Categories",},
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_name", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="images")),
                (
                    "date_published",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date published",
                    ),
                ),
                ("article_slug", models.CharField(default=1, max_length=200)),
                (
                    "subcategory_name",
                    models.ForeignKey(
                        default=1,
                        on_delete="SET_DEFAULT",
                        to="main.SubCategory",
                        verbose_name="SubCategory",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Articles",},
        ),
    ]
