# Generated by Django 2.2.4 on 2019-08-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_auto_20190816_2221"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subcategory_name", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("category_name", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Sub Categories",},
        ),
        migrations.DeleteModel(name="CardContainer",),
        migrations.AlterModelOptions(
            name="card", options={"verbose_name_plural": "Cards"},
        ),
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="card",
            old_name="container_name",
            new_name="subcat_name",
        ),
        migrations.RemoveField(model_name="category", name="container_name",),
    ]
