
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app-env
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  SECRET_KEY: 'azxey(r8ieohsd1qc93j*%@+1+@-c&kwbgugz2ojvb@sj=!4*c'
  EMAIL_HOST_USER: gbournique.dev@gmail.com
  EMAIL_HOST_PASSWORD: "2341234"

---

apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app-config
data:
  run_celery.sh: "\n#!/bin/sh\ncd /code/ \ncelery --app=myportfolio.celeryconf worker
    --loglevel=info --concurrency=10 -n worker1.%h\n"
  run_server.sh: |
    #!/bin/sh
    python manage.py collectstatic --no-input -v 0
    python manage.py makemigrations
    python manage.py migrate
    gunicorn myportfolio.wsgi:application --bind 0.0.0.0:8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        role: app
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: staticfiles
        hostPath:
          path: /data/staticfiles/
          type: Directory
      - name: mediafiles
        hostPath:
          path: /data/mediafiles/
          type: Directory
      - name: redisdata
        hostPath:
          path: /data/redisdata/
          type: Directory
      containers:
      - name: app
        image: docker.io/gbournique/myportfolio_app:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: DEBUG
              name: app-env
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              key: ALLOWED_HOSTS
              name: app-env
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: SECRET_KEY
              name: app-env
        - name: EMAIL_HOST_USER
          valueFrom:
            configMapKeyRef:
              key: EMAIL_HOST_USER
              name: app-env
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: EMAIL_HOST_PASSWORD
              name: app-env 
        volumeMounts:
        - name: staticfiles
          mountPath: /code/staticfiles/
          readOnly: false
        - name: mediafiles
          mountPath: /code/mediafiles/
          readOnly: false
        - name: redisdata
          mountPath: /data/
          readOnly: false
        - name: config-volume
          mountPath: /code/entrypoints/
          readOnly: false
        args:
        - bin/sh
        - -c
        - /code/entrypoints/run_server.sh
        ports:
        - containerPort: 8080
        resources: {}
        livenessProbe:
          exec:
            command:
            - bin/sh
            - -c
            - curl -f -s -S http://localhost:8080 || exit 1
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 5    
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        role: app
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: staticfiles
        hostPath:
          path: /data/staticfiles/
          type: Directory
      - name: mediafiles
        hostPath:
          path: /data/mediafiles/
          type: Directory
      - name: redisdata
        hostPath:
          path: /data/redisdata/
          type: Directory
      containers:
      - name: node-codewithdan
        image: docker.io/gbournique/myportfolio_app:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: DEBUG
              name: app-env
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              key: ALLOWED_HOSTS
              name: app-env
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: SECRET_KEY
              name: app-env
        - name: EMAIL_HOST_USER
          valueFrom:
            configMapKeyRef:
              key: EMAIL_HOST_USER
              name: app-env
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: EMAIL_HOST_PASSWORD
              name: app-env 
        volumeMounts:
        - name: staticfiles
          mountPath: /code/staticfiles/
          readOnly: false
        - name: mediafiles
          mountPath: /code/mediafiles/
          readOnly: false
        - name: redisdata
          mountPath: /data/
          readOnly: false
        - name: config-volume
          mountPath: /code/entrypoints/
          readOnly: false
        args:
        - bin/sh
        - -c
        - /code/entrypoints/run_celery.sh
        ports:
        - containerPort: 8080
        resources: {}
        livenessProbe:
          exec:
            command:
            - bin/sh
            - -c
            - ps | grep celery || exit 1
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080

---