apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: codewithdan/redis
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
