- name: Create and upload postgres backup to AWS S3 in test/ sub folder
  become_user: ubuntu
  shell: cd {{ PORTFOLIO_ROOT_DIR }} && source .env && make test-connection-postgres-backup
  args:
    executable: /bin/bash
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"