- name: Start instance(s)
  ec2:
    instance_ids:
      - "{{ ANSIBLE_INSTANCE_ID }}"
    region: "{{ AWS_DEFAULT_REGION }}"
    state: running
    wait: True
    assign_public_ip: yes

- name: Wait for ssh to come up
  wait_for:
    host: "{{ ANSIBLE_HOST_PUBLIC_DNS }}"
    port: 22
    delay: 10
    timeout: 300