---
# This playbook contains all actions that will be run on "local" host.

- name: Import dependencies installation tasks
  include_tasks: 1_setup_instance.yml
  tags:
    - setup-instance

- name: Cleaning up existing running stacks, containers, images and volumes
  include_tasks: 2_docker_prune.yml
  tags:
    - docker-prune

- name: Import Github repo download tasks
  include_tasks: 3_clone_repo.yml
  tags:
    - clone-repo

- name: Deploy a docker swarm production environment
  include_tasks: 4_deploy_stack.yml
  tags:
    - deploy-stack

- name: Backup postgres data to S3 bucket
  include_tasks: 5_backup_postgres.yml
  tags:
    - backup-postgres