version: "3.5"

services:
      
  app:
    build:
      context: ../..
      dockerfile: deployment/build-images/app.dockerfile
      args:
        app_component : "backend-app"
        app_debug: ${DEBUG}
    container_name: app
    restart: "no"
    environment:
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: "*"
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}