version: "3.7"

services:

  nginx:
    build:
      context: ../..
      dockerfile: deployment/build-images/nginx.dockerfile
    container_name: nginx
    restart: always
    volumes: 
      - static:/www/staticfiles/
      - media:/www/mediafiles/
    healthcheck:
      test: stat /etc/nginx/conf.d/nginx-prod.conf && curl localhost:80 || exit 1
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 20s
    ports: 
      - "80:80"
    networks:
      - proxy
    depends_on:
      - app
      
  app:
    build:
      context: ../..
      dockerfile: deployment/build-images/app.dockerfile
      args:
        app_component : "backend-app"
        app_debug: ${DEBUG}
    container_name: app
    restart: "no"
    environment:
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: "*"
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    volumes:
      - static:/code/staticfiles/
      - media:/code/mediafiles/
      - redisdata:/data
    healthcheck:
      test: curl -f -s -S http://localhost:8080 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    expose: 
      - 8080
    networks:
      - backend
      - proxy
    entrypoint:
      - ./run_server.sh
    depends_on:
      - postgres
      - redis

  postgres:
    build:
      context: ../..
      dockerfile: deployment/build-images/postgres.dockerfile
    container_name: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data/ 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - 5432
    networks:
      - backend

  redis:
    build:
      context: ../..
      dockerfile: deployment/build-images/redis.dockerfile
    container_name: redis
    restart: "no"
    volumes:
      - redisdata:/data
    healthcheck:
      test: bash /usr/local/bin/run_redis_healthcheck.sh
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - 6379
    networks:
      - backend
  
  celery:
    build:
      context: ../..
      dockerfile: deployment/build-images/app.dockerfile
      args:
        app_component : "backend-celery"
        app_debug: ${DEBUG}
    container_name: celery
    restart: "no"
    environment:
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: "*"
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    volumes:
      - static:/code/main/static/
      - media:/code/main/mediafiles/
      - redisdata:/data
    healthcheck:
      test: ps | grep celery || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    expose: 
      - 8080
    networks:
      - backend
      - proxy
    entrypoint:
      - ./run_celery.sh
    depends_on:
      - postgres
      - redis

volumes:
  static:
  media:
  pgdata:
  redisdata:

networks:
  backend:
    driver: bridge
  proxy:
    driver: bridge