apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portfolio-app.fullname" . }}-worker
  labels:
    {{- include "portfolio-app.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "portfolio-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "portfolio-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "portfolio-app.serviceAccountName" . }}
      securityContext:
        {{- include "portfolio-app.podSecurityContext" . | nindent 8 }}
      volumes:
        {{- include "portfolio-app.volumes" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- include "portfolio-app.securityContext" . | nindent 12 }}
          image: {{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          envFrom:
          {{- include "portfolio-app.portfolio-env" . | nindent 10 }}
          {{- include "portfolio-app.portfolio-secret" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "portfolio-app.volMounts" . | nindent 12 }}
          command: ["/bin/bash", "-c"]
          args:
          {{- if .Values.initialStartupDelay }}
            - >
              echo 'waiting {{ .Values.initialStartupDelay }}s...' &&
              sleep {{ .Values.initialStartupDelay }} &&
              . /home/portfoliouser/portfolio/app/startup_celery.sh
          {{- else -}}
            - >
              . /home/portfoliouser/portfolio/app/startup_celery.sh
          {{- end -}}