{{- $portfolioAppFullname := include "portfolio-app.fullname" . -}}

{{- range .Values.global.portfolio_secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $portfolioAppFullname }}-{{ .name }}
type: Opaque
data:
{{- range $key, $value := .data -}}
{{ $key | nindent 2 }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}
---
{{- end }}