
# create super user - use existing logic to automatically get the right container id?
# docker exec -it 1c37cd9c4bf7 python manage.py createsuperuser


# docker compose update
# docker-compose down && docker-compose build && docker-compose up