# Generated by Django 2.2.4 on 2019-08-16 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=200)),
                ('card_summary', models.CharField(max_length=200)),
                ('card_content', models.TextField()),
                ('card_length', models.CharField(max_length=20)),
                ('card_image', models.ImageField(upload_to='images/')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('container_name', models.CharField(max_length=200)),
                ('tutorial_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=200)),
                ('container_location', models.CharField(max_length=200)),
                ('container_duration', models.CharField(max_length=200)),
                ('container_summary', models.TextField()),
                ('container_image', models.ImageField(upload_to='images/')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_summary', models.TextField()),
                ('category_image', models.ImageField(upload_to='images/')),
                ('container_name', models.CharField(max_length=200)),
            ],
        ),
    ]
