# Generated by Django 2.2.4 on 2019-08-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='tutorial_slug',
            new_name='card_slug',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_length',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='cardcontainer',
            old_name='container_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='cardcontainer',
            old_name='container_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cardcontainer',
            old_name='container_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='cardcontainer',
            old_name='container_summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_summary',
            new_name='summary',
        ),
    ]
