local_dev:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: python

docker_qa:
  hosts:
    launched:
      ansible_host: launched
      ansible_user: ubuntu
      ansible_ssh_pass: "{{ lookup('env','ANSIBLE_SSH_PASSWORD') }}"
      ansible_become: true