local_dev:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: python

docker_qa:
  hosts:
    35.176.145.214:
      ansible_host: 35.176.145.214
      ansible_user: ubuntu
      ansible_ssh_pass: "{{ lookup('env','ANSIBLE_SSH_PASSWORD') }}"
      ansible_become: true

kubernetes_qa:
  hosts:
    35.176.145.214:
      ansible_host: 35.176.145.214
      ansible_user: ubuntu
      ansible_ssh_pass: "{{ lookup('env','ANSIBLE_SSH_PASSWORD') }}"
      ansible_become: true