local_dev:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: python

# test
docker_qa:
  hosts:
    host_1:
      ansible_host: launched
      ansible_user: ec2-user
      ansible_ssh_pass: "{{ lookup('env','ANSIBLE_SSH_PASSWORD') }}"
      ansible_become: true