### Playbook to test docker deployment scripts

- name: Start AWS instance
  hosts: localhost
  gather_facts: true
  roles:
    - start_instance

- name: Starting docker-compose services
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - setup_instance
    - prepare_deployment
    - docker_compose_up
    - test_postgres_backup

- name: Send slack notification
  hosts: localhost
  gather_facts: true
  roles:
    - send_slack_notification
  tags:
    - slack-notification

- name: Pause playbook
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - pause_playbook

- name: Stopping docker-compose services
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - docker_compose_down