### Playbook for a fresh (not an upgrade) docker deployment

- name: Start AWS instance
  hosts: localhost
  gather_facts: true
  roles:
    - start_instance

- name: Deployment steps - 1/2
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - setup_instance
    - prepare_deployment
    - docker_compose_up

- name: Send notification
  hosts: localhost
  gather_facts: true
  roles:
    - send_email_notification

- name: Deployment steps - 2/2
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - pause_playbook
    - docker_compose_down

- name: Stop AWS instance
  hosts: localhost
  gather_facts: true
  roles:
    - stop_instance

