### Playbook for a fresh (not an upgrade) docker deployment

- name: Start AWS instance
  hosts: localhost
  gather_facts: true
  roles:
    - start_instance

- name: Starting docker-compose services
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - setup_instance
    - prepare_deployment
    - docker_compose_up

- name: Send notification
  hosts: localhost
  gather_facts: true
  roles:
    - send_slack_notification

- name: Create and upload Postgres dump to S3
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - postgres_dump_to_s3
  tags:
    - postgres-dump

- name: Load latest Postgres dump from S3
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - postgres_restore_from_s3
  tags:
    - postgres-restore

- name: Stopping docker-compose services
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - pause_playbook
    - docker_compose_down
  tags:
    - compose-down

- name: Stop AWS instance
  hosts: localhost
  gather_facts: true
  roles:
    - stop_instance
  tags:
    - stop-instance

