### Playbook for a fresh (not an upgrade) docker deployment

- name: Create and upload Postgres dump to S3
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - postgres_dump_to_s3
  tags:
    - postgres-dump

- name: Load latest Postgres dump from S3
  hosts: docker_qa
  remote_user: ubuntu
  become: yes
  roles:
    - postgres_restore_from_s3
  tags:
    - postgres-restore