### Playbook to stop ec2 instance

- name: Stop AWS instance
  hosts: localhost
  gather_facts: true
  vars:
    region: eu-west-2
    tag_name_value: "QA temp instance launched by Ansible"
  tasks:
    - name: Filter EC2 to be stopped
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ tag_name_value }}"
      register: ec2
    - name: Stop instances
      ec2:
        region: "{{ region }}"
        state: 'stopped'
        instance_ids: '{{ item.instance_id }}'
      with_items: "{{ ec2.instances }}"
      ignore_errors: True