
- name: docker-compose up
  become_user: ec2-user
  shell: >
    cd {{ PORTFOLIO_ROOT_DIR }} &&
    cd deployment/ &&
    source .env &&
    make up
  args:
    executable: /bin/bash
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"

- name: Check all services are healthy
  become_user: ec2-user
  shell: >
    cd {{ PORTFOLIO_ROOT_DIR }}/deployment/ &&
    source .env &&
    make check-services-health
  args:
    executable: /bin/bash
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"

- name: Wait until webserver is running
  uri:
    url: "http://{{ ANSIBLE_HOST_NAME }}"
    method: GET
    validate_certs: no
  register: _result
  until: _result.status == 200
  delay: 10 # Check every 10 seconds
  retries: 3