---
# This playbook contains all actions that will be run on "local" host.


- name: Stop instances tagged with type=swarm
  ec2:
    region: eu-west-3
    instance_tags:
        Type: "{{ INSTANCE_TAG_TYPE }}"
    state: stopped
  tags:
    - stop-instance
