---
# This playbook contains all actions that will be run on "local" host.

- name: Running postgres backup script
  shell: cd {{ REPO_LOCAL_PATH }}/cluster-management/utils && bash backup-postgres.sh myportfolio_postgres myportfoliodb
  register: cmdln
  ignore_errors: yes
  tags:
    - stop-instance

- name: Stop instances tagged with type=swarm
  ec2:
    region: eu-west-3
    instance_tags:
        Type: "{{ INSTANCE_TAG_TYPE }}"
    state: stopped
  tags:
    - stop-instance